image:
  file: .gitpod.Dockerfile

tasks:
  - init: 
          mvn install -DskipTests=false
          javac app.java
    command: java app
  - before: sdk install java 21.0.2-amzn < /dev/null

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore